// builder.go — conversational agent builder engine.
//
// The Builder turns a user's vague natural-language idea into a complete
// agent specification (SOUL.yaml) through a guided conversation. It uses a
// carefully crafted system prompt that:
//   - Asks exactly one question per turn (never lists of questions)
//   - Infers as much as possible from what the user already said
//   - Produces a structured UNDERSTANDING JSON block alongside every reply
//   - Knows when it has enough information to offer a confirmation and generate
//
// Each builder session is independent and lives in memory. Sessions expire
// after 2 hours of inactivity (cleaned up on next use).
package runtime

import (
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"sync"
	"time"
	"unicode"

	"go.uber.org/zap"

	"github.com/soulacy/soulacy/internal/agentprompt"
	"github.com/soulacy/soulacy/internal/llm"
)

// ── Types ─────────────────────────────────────────────────────────────────────

// BuilderUnderstanding is the structured spec the builder LLM builds up over
// the course of a conversation. It maps directly to a SOUL.yaml on generation.
type BuilderUnderstanding struct {
	Name         string          `json:"name"`
	Description  string          `json:"description"`
	Confidence   float64         `json:"confidence"`
	Trigger      *BuilderTrigger `json:"trigger"`
	Purpose      string          `json:"purpose"`
	SystemPrompt string          `json:"system_prompt"`
	Tools        []BuilderTool   `json:"tools"`
	Memory       *BuilderMemory  `json:"memory"`
	Outputs      []BuilderOutput `json:"outputs"`
	Missing      []string        `json:"missing"`
}

// BuilderTrigger describes how the agent is activated.
type BuilderTrigger struct {
	Type     string   `json:"type"`     // "cron" | "channel" | "manual"
	Schedule string   `json:"schedule"` // cron expression if type=cron
	Channels []string `json:"channels"` // e.g. ["whatsapp","http"]
}

// BuilderTool is an external capability the agent needs (becomes a tool in SOUL.yaml).
type BuilderTool struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

// BuilderMemory describes the agent's memory requirements.
type BuilderMemory struct {
	Needs bool   `json:"needs"`
	Scope string `json:"scope"` // "session" | "global"
}

// BuilderOutput describes where the agent sends its results.
type BuilderOutput struct {
	Channel     string `json:"channel"`
	Description string `json:"description"`
}

// BuilderResponse is returned to the gateway handler after each turn.
type BuilderResponse struct {
	SessionID     string                `json:"session_id"`
	Reply         string                `json:"reply"`
	Understanding *BuilderUnderstanding `json:"understanding"`
	Ready         bool                  `json:"ready"`
}

// builderSession holds the conversation history for one builder session.
type builderSession struct {
	ID            string
	History       []llm.ChatMessage
	Understanding *BuilderUnderstanding
	mu            sync.Mutex
	LastActive    time.Time
}

// ── Engine methods ────────────────────────────────────────────────────────────

// BuilderChat processes one turn of the agent builder conversation.
// provider is the LLM provider to use (e.g. "ollama", "openai").
// sessionID should be a UUID generated by the client for the first turn
// and reused for all subsequent turns.
// catalog is an optional pre-formatted string listing real tools available to
// agents (python files in ~/.soulacy/tools/, MCP server tools, built-ins).
// When non-empty, it's injected as an extra system message so the Builder LLM
// picks REAL tool names instead of inventing mcp__* placeholders.
func (e *Engine) BuilderChat(ctx context.Context, sessionID, message, provider, catalog string) (*BuilderResponse, error) {
	sess := e.getOrCreateBuilderSession(sessionID)

	sess.mu.Lock()
	sess.History = append(sess.History, llm.ChatMessage{Role: "user", Content: message})
	trimBuilderHistoryLocked(sess)
	msgs := buildBuilderMessages(sess.History)
	if brief := understandingBrief(sess.Understanding); brief != "" {
		msgs = append([]llm.ChatMessage{msgs[0], {Role: "system", Content: brief}}, msgs[1:]...)
	}
	if catalog != "" {
		// Inject AFTER the system prompt, BEFORE the conversation history, so
		// every turn sees the catalog without baking it into stored history.
		header := llm.ChatMessage{Role: "system", Content: catalog}
		msgs = append([]llm.ChatMessage{msgs[0], header}, msgs[1:]...)
	}
	sess.mu.Unlock()

	e.log.Debug("builder chat",
		zap.String("session", sessionID),
		zap.String("preview", truncate(message, 60)),
	)

	// Request a single JSON object {reply, understanding} via the provider's
	// native structured-output mode. This is dramatically more reliable than
	// the legacy REPLY:/UNDERSTANDING: marker format — local models like
	// llama3.3:70b drift away from markers by turn 3-4, leaving the Blueprint
	// stuck at 0% confidence. JSON-mode is enforced by the provider itself.
	resp, err := e.llmRouter.Complete(ctx, provider, llm.CompletionRequest{
		Messages:    msgs,
		Temperature: 0.6,
		// 1500 was not enough. A reasoning model spends part of the same budget
		// thinking before it writes, so the visible JSON was being cut off
		// mid-object — and a builder reply that does not parse costs the user a
		// whole exchange. The envelope itself is small; the headroom is for the
		// model's own preamble.
		MaxTokens:      4000,
		ResponseFormat: "json_schema",
		JSONSchema:     builderResponseSchema,
	})
	if err != nil {
		return nil, fmt.Errorf("builder: llm: %w", err)
	}

	reply, understanding := parseBuilderResponse(resp.Content)

	sess.mu.Lock()
	// Store what the assistant actually said, not the raw model output. A
	// truncated JSON fragment in the history is worse than useless: the model
	// reads it back next turn and follows it off a cliff.
	stored := resp.Content
	if understanding == nil && looksLikeJSON(resp.Content) {
		stored = reply
	}
	sess.History = append(sess.History, llm.ChatMessage{Role: "assistant", Content: stored})
	trimBuilderHistoryLocked(sess)
	if understanding != nil {
		sess.Understanding = understanding
	}
	sess.LastActive = time.Now()
	sess.mu.Unlock()

	// The user may already have answered in plain words. Reading the time out
	// of what they typed stops the conversation asking again for something
	// they have said, which is how a builder loses someone's patience.
	if understanding != nil && understanding.Trigger != nil &&
		strings.EqualFold(strings.TrimSpace(understanding.Trigger.Type), "cron") &&
		strings.TrimSpace(understanding.Trigger.Schedule) == "" {
		if cron := cronFromPlainTime(message); cron != "" {
			understanding.Trigger.Schedule = cron
		}
	}

	// Fold any gap the model did not notice back into `missing`, so the next
	// turn asks about it. The model reads this field; a gap it cannot see is a
	// gap it will never ask the user to fill.
	if gaps := buildableGaps(understanding); len(gaps) > 0 && understanding != nil {
		have := map[string]bool{}
		for _, m := range understanding.Missing {
			have[strings.ToLower(strings.TrimSpace(m))] = true
		}
		for _, g := range gaps {
			if !have[strings.ToLower(g)] {
				understanding.Missing = append(understanding.Missing, g)
			}
		}
	}

	ready := understanding != nil &&
		understanding.Confidence >= 0.8 &&
		len(understanding.Missing) == 0

	return &BuilderResponse{
		SessionID:     sessionID,
		Reply:         reply,
		Understanding: understanding,
		Ready:         ready,
	}, nil
}

// BuilderGenerate compiles a BuilderUnderstanding into a SOUL.yaml string
// and a JSON-serialisable agent map ready to POST to /api/v1/agents.
func (e *Engine) BuilderGenerate(u *BuilderUnderstanding, provider, model string) (soulYAML string, agentMap map[string]any) {
	soulYAML = generateSOULYAML(u, provider, model)
	agentMap = understandingToAgentMap(u, provider, model)
	return
}

// GetBuilderUnderstanding returns the current understanding for an existing
// builder session, or nil if the session doesn't exist yet.
func (e *Engine) GetBuilderUnderstanding(sessionID string) *BuilderUnderstanding {
	val, ok := e.builderSessions.Load(sessionID)
	if !ok {
		return nil
	}
	sess := val.(*builderSession)
	sess.mu.Lock()
	defer sess.mu.Unlock()
	return sess.Understanding
}

// DeleteBuilderSession removes a builder session from memory.
func (e *Engine) DeleteBuilderSession(sessionID string) {
	e.builderSessions.Delete(sessionID)
}

// ── Builder session management ────────────────────────────────────────────────

// Builder sessions are keyed by a CLIENT-SUPPLIED session id and were only ever
// removed by an explicit DELETE. LastActive was written on every turn and read
// nowhere; the package doc above promised a 2-hour expiry that did not exist. A
// caller holding builder:write could therefore pin unbounded memory by varying
// the id, and History grew without limit within a single session because the
// user message is appended BEFORE the LLM call — so even a failing provider
// still cost memory per request.
const (
	builderSessionTTL      = 2 * time.Hour
	maxBuilderSessions     = 200
	maxBuilderHistoryTurns = 60 // 30 exchanges; the Blueprint is summarised, not replayed
)

func (e *Engine) getOrCreateBuilderSession(id string) *builderSession {
	e.sweepBuilderSessions()
	val, _ := e.builderSessions.LoadOrStore(id, &builderSession{
		ID:         id,
		LastActive: time.Now(),
	})
	sess := val.(*builderSession)
	sess.mu.Lock()
	sess.LastActive = time.Now()
	sess.mu.Unlock()
	return sess
}

// sweepBuilderSessions drops sessions idle past the TTL, and — if the map is
// still over the cap after that — the least recently active ones. The cap is the
// part that actually bounds memory: a caller can create sessions far faster than
// the TTL retires them.
func (e *Engine) sweepBuilderSessions() {
	type aged struct {
		id   string
		last time.Time
	}
	cutoff := time.Now().Add(-builderSessionTTL)
	var live []aged
	e.builderSessions.Range(func(k, v any) bool {
		sess, ok := v.(*builderSession)
		if !ok {
			return true
		}
		sess.mu.Lock()
		last := sess.LastActive
		sess.mu.Unlock()
		if last.Before(cutoff) {
			e.builderSessions.Delete(k)
			return true
		}
		if id, ok := k.(string); ok {
			live = append(live, aged{id: id, last: last})
		}
		return true
	})
	// Note the "-1" and the "<": the sweep runs BEFORE the caller inserts, so it
	// has to leave room for the session about to be created. Trimming to exactly
	// maxBuilderSessions here means the map settles at maxBuilderSessions+1.
	if len(live) < maxBuilderSessions {
		return
	}
	sort.Slice(live, func(i, j int) bool { return live[i].last.Before(live[j].last) })
	for _, a := range live[:len(live)-maxBuilderSessions+1] {
		e.builderSessions.Delete(a.id)
	}
}

// trimBuilderHistoryLocked keeps the most recent turns. Caller holds sess.mu.
func trimBuilderHistoryLocked(sess *builderSession) {
	if len(sess.History) > maxBuilderHistoryTurns {
		sess.History = append([]llm.ChatMessage(nil), sess.History[len(sess.History)-maxBuilderHistoryTurns:]...)
	}
}

func buildBuilderMessages(history []llm.ChatMessage) []llm.ChatMessage {
	msgs := make([]llm.ChatMessage, 0, len(history)+1)
	msgs = append(msgs, llm.ChatMessage{Role: "system", Content: builderSystemPrompt})
	msgs = append(msgs, history...)
	return msgs
}

// understandingBrief restates what has already been established, as an
// authoritative system message on every turn.
//
// The model's only memory used to be the raw text of its own previous
// replies. When one of those replies was truncated — which happens — the
// history it read back was a broken JSON fragment, and it lost the thread:
// in a real session it collected the purpose, the topic and the destination,
// then asked for the purpose again as if the conversation had just started.
//
// Understanding is accumulated server-side and survives a bad turn, so
// handing it back each time means a single truncation costs one exchange
// instead of the whole conversation.
func understandingBrief(u *BuilderUnderstanding) string {
	if u == nil {
		return ""
	}
	var b strings.Builder
	b.WriteString("## Already established — do not ask about these again\n")
	add := func(label, v string) {
		if strings.TrimSpace(v) != "" {
			fmt.Fprintf(&b, "- %s: %s\n", label, v)
		}
	}
	add("Agent name", u.Name)
	add("What it does", u.Purpose)
	add("Description", u.Description)
	if u.Trigger != nil {
		add("Trigger", u.Trigger.Type)
		add("Schedule (cron)", u.Trigger.Schedule)
		if len(u.Trigger.Channels) > 0 {
			add("Channels", strings.Join(u.Trigger.Channels, ", "))
		}
	}
	if len(u.Tools) > 0 {
		names := make([]string, 0, len(u.Tools))
		for _, t := range u.Tools {
			names = append(names, t.Name)
		}
		add("Tools", strings.Join(names, ", "))
	}
	if len(u.Outputs) > 0 {
		chans := make([]string, 0, len(u.Outputs))
		for _, o := range u.Outputs {
			chans = append(chans, o.Channel)
		}
		add("Sends results to", strings.Join(chans, ", "))
	}
	if strings.TrimSpace(u.SystemPrompt) != "" {
		b.WriteString("- The agent's instructions have already been drafted; carry them forward unchanged unless the user asks to change them.\n")
	}
	if len(u.Missing) > 0 {
		fmt.Fprintf(&b, "\nStill needed: %s\n", strings.Join(u.Missing, ", "))
	}
	// Only worth sending when something is actually known.
	if strings.Count(b.String(), "\n") <= 1 {
		return ""
	}
	b.WriteString("\nRepeat every field above in your next `understanding` object. Dropping one loses it.")
	return b.String()
}

// ── Response parser ───────────────────────────────────────────────────────────

// tryParseBuilderJSON attempts to parse the LLM response as the canonical
// {reply, understanding} object. Tolerates code fences, leading prose, and
// trailing chatter — anything that still wraps a parseable JSON object.
func tryParseBuilderJSON(content string) (string, *BuilderUnderstanding, bool) {
	s := strings.TrimSpace(content)
	// Strip ```json fences if present.
	if strings.HasPrefix(s, "```") {
		s = strings.TrimPrefix(s, "```json")
		s = strings.TrimPrefix(s, "```")
		s = strings.TrimSuffix(s, "```")
		s = strings.TrimSpace(s)
	}
	// Find the outermost {...} — accommodates prefatory prose the model leaks.
	first := strings.Index(s, "{")
	last := strings.LastIndex(s, "}")
	if first < 0 || last <= first {
		return "", nil, false
	}
	var env struct {
		Reply         string                `json:"reply"`
		Understanding *BuilderUnderstanding `json:"understanding"`
	}
	if err := json.Unmarshal([]byte(s[first:last+1]), &env); err != nil {
		return "", nil, false
	}
	if env.Reply == "" && env.Understanding == nil {
		return "", nil, false
	}
	// If the model returned only understanding (no prose), synthesise a short
	// prompt so the user sees something in the chat instead of a blank bubble.
	if env.Reply == "" && env.Understanding != nil {
		if len(env.Understanding.Missing) > 0 {
			env.Reply = "Got it. Could you tell me about: " + strings.Join(env.Understanding.Missing, ", ") + "?"
		} else {
			env.Reply = "Got it — anything else I should know?"
		}
	}
	return env.Reply, env.Understanding, true
}

// builderResponseSchema is the JSON Schema we pass to the provider so the LLM
// is forced to emit a single object with `reply` and `understanding` fields.
// All providers (OpenAI, Anthropic, Gemini, Ollama ≥ 0.5) honor this via
// ResponseFormat=json_schema in CompletionRequest.
var builderResponseSchema = map[string]any{
	"type":                 "object",
	"additionalProperties": false,
	"required":             []string{"reply", "understanding"},
	"properties": map[string]any{
		"reply": map[string]any{
			"type":        "string",
			"description": "Your conversational message to the user — warm, direct, ONE question if anything is unclear.",
		},
		"understanding": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"name":        map[string]any{"type": []string{"string", "null"}},
				"description": map[string]any{"type": []string{"string", "null"}},
				"confidence":  map[string]any{"type": "number"},
				"purpose":     map[string]any{"type": []string{"string", "null"}},
				"system_prompt": map[string]any{
					"type":        []string{"string", "null"},
					"description": "The full, detailed instructions the deployed agent will see on every run. MUST preserve the user's original procedure verbatim — including step-by-step numbered lists, specific cron times, chat IDs, URLs, API names, tool invocations. Multi-paragraph is encouraged. Do NOT summarise.",
				},
				"trigger": map[string]any{
					"type": []string{"object", "null"},
					"properties": map[string]any{
						"type":     map[string]any{"type": []string{"string", "null"}},
						"schedule": map[string]any{"type": []string{"string", "null"}},
						"channels": map[string]any{
							"type":  "array",
							"items": map[string]any{"type": "string"},
						},
					},
				},
				"tools": map[string]any{
					"type": "array",
					"items": map[string]any{
						"type": "object",
						"properties": map[string]any{
							"name":        map[string]any{"type": "string"},
							"description": map[string]any{"type": "string"},
						},
						"required": []string{"name", "description"},
					},
				},
				"memory": map[string]any{
					"type": []string{"object", "null"},
					"properties": map[string]any{
						"needs": map[string]any{"type": []string{"boolean", "null"}},
						"scope": map[string]any{"type": []string{"string", "null"}},
					},
				},
				"outputs": map[string]any{
					"type": "array",
					"items": map[string]any{
						"type": "object",
						"properties": map[string]any{
							"channel":     map[string]any{"type": "string"},
							"description": map[string]any{"type": "string"},
						},
					},
				},
				"missing": map[string]any{
					"type":  "array",
					"items": map[string]any{"type": "string"},
				},
			},
			"required": []string{"confidence"},
		},
	},
}

// parseBuilderResponse splits an LLM response into the conversational REPLY
// and the structured UNDERSTANDING JSON. Now JSON-mode first (the canonical
// shape produced by structured-output providers), with the legacy REPLY:/
// UNDERSTANDING: marker format as a fallback for any provider that ignores
// our response_format hint.
func parseBuilderResponse(content string) (reply string, understanding *BuilderUnderstanding) {
	// Path 1 — canonical: a single JSON object {reply, understanding}.
	if r, u, ok := tryParseBuilderJSON(content); ok {
		return r, u
	}

	// Path 2 — legacy: REPLY:/UNDERSTANDING: markers (kept for safety net).
	replyIdx := strings.Index(content, "REPLY:")
	underIdx := strings.Index(content, "UNDERSTANDING:")

	if replyIdx >= 0 && underIdx > replyIdx {
		reply = strings.TrimSpace(content[replyIdx+6 : underIdx])
		jsonPart := strings.TrimSpace(content[underIdx+14:])

		start := strings.Index(jsonPart, "{")
		end := strings.LastIndex(jsonPart, "}")
		if start >= 0 && end > start {
			u := &BuilderUnderstanding{}
			if err := json.Unmarshal([]byte(jsonPart[start:end+1]), u); err == nil {
				understanding = u
			}
		}
	} else if replyIdx >= 0 {
		reply = strings.TrimSpace(content[replyIdx+6:])
	} else if looksLikeJSON(content) {
		// The model meant to answer in JSON and the JSON did not parse — almost
		// always because the reply was truncated mid-object. Showing the raw
		// fragment puts a wall of braces on the user's screen and reads as the
		// product being broken. Say something true and short instead, and
		// return no understanding so the caller keeps the last good one.
		reply = "Sorry — my answer got cut off. Could you say that again, or add a little more detail?"
	} else {
		// No markers — use full content as reply, try to find embedded JSON
		reply = strings.TrimSpace(content)
		if start := strings.LastIndex(content, "```json"); start >= 0 {
			end := strings.LastIndex(content, "```")
			if end > start+7 {
				reply = strings.TrimSpace(content[:start])
				jsonStr := strings.TrimSpace(content[start+7 : end])
				u := &BuilderUnderstanding{}
				if err := json.Unmarshal([]byte(jsonStr), u); err == nil {
					understanding = u
				}
			}
		}
	}

	// Clean up reply — remove trailing code fences or JSON leakage
	if idx := strings.Index(reply, "```"); idx >= 0 {
		reply = strings.TrimSpace(reply[:idx])
	}

	return
}

// ── SOUL.yaml generator ───────────────────────────────────────────────────────

func generateSOULYAML(u *BuilderUnderstanding, provider, model string) string {
	id := sanitizeID(u.Name)
	if id == "" {
		id = "my-agent"
	}
	description := u.Description
	if description == "" {
		description = u.Purpose
	}
	humanName := toTitleCase(strings.ReplaceAll(id, "-", " "))

	triggerType := "channel"
	scheduleBlock := ""
	channelsBlock := "channels: [http]"

	if u.Trigger != nil {
		switch u.Trigger.Type {
		case "cron":
			triggerType = "cron"
			if u.Trigger.Schedule != "" {
				scheduleBlock = fmt.Sprintf("schedule: %q\n", u.Trigger.Schedule)
			}
			channelsBlock = ""
		case "channel":
			chs := u.Trigger.Channels
			if len(chs) == 0 {
				chs = []string{"http"}
			}
			channelsBlock = fmt.Sprintf("channels: [%s]", strings.Join(chs, ", "))
		case "manual":
			triggerType = "channel"
		}
	}

	// Prefer the detailed system_prompt the Builder produces — it captures the
	// user's full procedure verbatim (multi-step plans, specific cron times,
	// chat IDs, URLs). Fall back to purpose for older sessions that didn't
	// populate system_prompt.
	sysPrompt := u.SystemPrompt
	if sysPrompt == "" {
		sysPrompt = u.Purpose
	}
	if sysPrompt == "" {
		sysPrompt = "You are a helpful AI assistant."
	}
	sysPrompt = agentprompt.EnsureShared(sysPrompt)
	sysPromptIndented := strings.ReplaceAll(sysPrompt, "\n", "\n  ")

	// Tool names only. This used to write `python_file: tools/<name>.py` for
	// every tool, whatever kind it was, and no such file was ever created —
	// so a preview a user could reasonably trust described wiring that did not
	// exist. The gateway resolves each name against the live catalog at deploy
	// time, which is the only place that knows what kind of tool it is.
	toolsBlock := ""
	if len(u.Tools) > 0 {
		var sb strings.Builder
		sb.WriteString("\n# Tools chosen for this agent. Resolved to built-ins, MCP tools or")
		sb.WriteString("\n# Python tools when deployed.")
		sb.WriteString("\ntool_names:")
		for _, t := range u.Tools {
			sb.WriteString(fmt.Sprintf("\n  - %s", t.Name))
		}
		toolsBlock = sb.String()
	}

	readScopes := "[session]"
	writeScopes := "[session]"
	if u.Memory != nil {
		if !u.Memory.Needs {
			readScopes = "[]"
			writeScopes = "[]"
		} else if u.Memory.Scope == "global" {
			readScopes = "[session, global]"
			writeScopes = "[session, global]"
		}
	}

	var out strings.Builder
	out.WriteString(fmt.Sprintf("id: %s\n", id))
	out.WriteString(fmt.Sprintf("name: %s\n", humanName))
	out.WriteString(fmt.Sprintf("description: %q\n", description))
	out.WriteString("version: \"1.0\"\n\n")
	out.WriteString(fmt.Sprintf("trigger: %s\n", triggerType))
	if scheduleBlock != "" {
		out.WriteString(scheduleBlock)
	}
	if channelsBlock != "" {
		out.WriteString(channelsBlock + "\n")
	}
	out.WriteString("\nsystem_prompt: |\n")
	out.WriteString(fmt.Sprintf("  %s\n", sysPromptIndented))
	out.WriteString("\nllm:\n")
	out.WriteString(fmt.Sprintf("  provider: %s\n", provider))
	out.WriteString(fmt.Sprintf("  model: %s\n", model))
	out.WriteString("  temperature: 0.7\n")
	out.WriteString("  max_tokens: 1024\n")
	if toolsBlock != "" {
		out.WriteString(toolsBlock)
		out.WriteString("\n")
	}
	out.WriteString("\nmemory:\n")
	out.WriteString(fmt.Sprintf("  read_scopes: %s\n", readScopes))
	out.WriteString(fmt.Sprintf("  write_scopes: %s\n", writeScopes))
	out.WriteString("  max_tokens: 50\n")
	out.WriteString("\nmax_turns: 10\n")
	out.WriteString("enabled: true\n")

	return out.String()
}

func understandingToAgentMap(u *BuilderUnderstanding, provider, model string) map[string]any {
	id := sanitizeID(u.Name)
	if id == "" {
		id = "my-agent"
	}
	description := u.Description
	if description == "" {
		description = u.Purpose
	}

	trigger := "channel"
	channels := []string{"http"}
	schedule := ""

	if u.Trigger != nil {
		switch u.Trigger.Type {
		case "cron":
			trigger = "cron"
			schedule = u.Trigger.Schedule
			channels = nil
		case "channel":
			if len(u.Trigger.Channels) > 0 {
				channels = u.Trigger.Channels
			}
		}
	}

	sysPrompt := u.SystemPrompt
	if sysPrompt == "" {
		sysPrompt = u.Purpose
	}
	if sysPrompt == "" {
		sysPrompt = "You are a helpful AI assistant."
	}

	readScopes := []string{"session"}
	writeScopes := []string{"session"}
	if u.Memory != nil && !u.Memory.Needs {
		readScopes = []string{}
		writeScopes = []string{}
	} else if u.Memory != nil && u.Memory.Scope == "global" {
		readScopes = []string{"session", "global"}
		writeScopes = []string{"session", "global"}
	}

	m := map[string]any{
		"id":            id,
		"name":          toTitleCase(strings.ReplaceAll(id, "-", " ")),
		"description":   description,
		"version":       "1.0",
		"trigger":       trigger,
		"system_prompt": sysPrompt,
		"llm": map[string]any{
			"provider":    provider,
			"model":       model,
			"temperature": 0.7,
			"max_tokens":  1024,
		},
		"memory": map[string]any{
			"read_scopes":  readScopes,
			"write_scopes": writeScopes,
			"max_tokens":   50,
		},
		// Enough room to call a tool, read the result and write the answer.
		// At ten, an agent that fetched market data ran out before it could
		// write anything, and the user was shown the raw tool payload as its
		// first result — which is the worst possible first impression.
		"max_turns": 25,
		"enabled":   true,
	}
	if trigger == "channel" && len(channels) > 0 {
		m["channels"] = channels
	}
	if schedule != "" {
		// agent.Definition.Schedule is *Schedule{Cron, At, Timeout} — use object form.
		m["schedule"] = map[string]any{"cron": schedule}
	}
	// Names only, for the same reason as the YAML above: this layer does not
	// know whether a chosen tool is a built-in, an MCP tool or a Python file,
	// and inventing a path for it produced agents whose tools pointed at
	// nothing. The gateway resolves these against the live catalog on deploy.
	if len(u.Tools) > 0 {
		names := make([]string, len(u.Tools))
		for i, t := range u.Tools {
			names[i] = t.Name
		}
		m["tool_names"] = names
	}
	return m
}

// ── String helpers ────────────────────────────────────────────────────────────

func sanitizeID(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	var out strings.Builder
	prevHyphen := false
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			out.WriteRune(r)
			prevHyphen = false
		} else if r == '-' || r == ' ' || r == '_' {
			if !prevHyphen && out.Len() > 0 {
				out.WriteRune('-')
				prevHyphen = true
			}
		}
	}
	result := strings.TrimSuffix(out.String(), "-")
	if len(result) > 64 {
		result = result[:64]
	}
	return result
}

func toTitleCase(s string) string {
	words := strings.Fields(s)
	for i, w := range words {
		if len(w) > 0 {
			runes := []rune(w)
			runes[0] = unicode.ToUpper(runes[0])
			words[i] = string(runes)
		}
	}
	return strings.Join(words, " ")
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

// ── System prompt ─────────────────────────────────────────────────────────────

const builderSystemPrompt = `You are the Soulacy Agent Builder — a conversational assistant that helps people design AI agents through friendly dialogue.

## Your mission
Turn a user's vague idea into a precise, deployable agent specification. Do this through targeted questions — one at a time, never a list. Speak plain English. Never use technical jargon unless the user uses it first.

## REQUIRED response format
Every single response MUST be a single JSON object with exactly two top-level fields:

{
  "reply":         "<your conversational message — warm, direct, one question if anything is unclear>",
  "understanding": { ... see schema below ... }
}

Return ONLY this JSON object. No prose before or after. No code fences. No markdown headers. The platform will display the "reply" field to the user; the "understanding" field is read programmatically and MUST be updated every turn (never omit).

## understanding schema
{
  "name":        "kebab-case-agent-name" | null,
  "description": "one-sentence summary of what the agent does" | null,
  "confidence":  0.0,
  "purpose":     "in plain English, what should the LLM core do?" | null,
  "system_prompt": "the role-specific instructions for this agent — the shared contract is added for you, do not repeat it" | null,
  "trigger": {
    "type":     "cron" | "channel" | "manual" | null,
    "schedule": "cron expression like '0 7 * * *'" | null,
    "channels": ["http", "telegram", ...]
  } | null,
  "tools":   [{"name": "kebab-case", "description": "..."}],
  "memory":  {"needs": true | false | null, "scope": "session" | "global" | null} | null,
  "outputs": [{"channel": "telegram | http | ...", "description": "..."}],
  "missing": ["short label for each thing still unclear"]
}

## CRITICAL — preserving the user's procedure
The "system_prompt" field is the actual instructions the deployed agent will see on every run. It is NOT a summary — it is the operating procedure.
- Write ONLY the role-specific instructions. The shared Soulacy Agent Operating Contract is prepended automatically when the agent is built, so do not reproduce it — copying it here wastes most of your output budget and gets your reply truncated mid-JSON.
- Copy the user's numbered steps VERBATIM into system_prompt.
- Preserve every specific value the user gave: cron times, dates, chat IDs, URLs, API endpoints, tool names, regex patterns, search queries.
- If the user said "every morning at 7 AM", the cron MUST be "0 7 * * *" (not 8 or 9). NEVER change a time the user gave you.
- If the user said "send to Telegram chat 8546291328", put that exact ID into system_prompt and mention it in the tool's description.
- Multi-paragraph system_prompts are encouraged when the user described a multi-step procedure. Don't compress.
- Add a final "Important:" paragraph noting failure modes and constraints you inferred.

## The reply field is spoken to the user
The reply field is one or two sentences addressed to the person, and nothing
else. It is never a list of what they have told you, never your working out,
never a note to yourself about what to check next. If you need to think, do it
before you write; the user sees only this field.

## Where results go
Results appear in Soulacy itself unless the user asks for somewhere else. Never
block on a delivery channel, never ask the user to name a "channel adapter",
and never treat "show it to me" or "on my phone" as an unanswered question —
both mean the default. Only record an external channel (Telegram, Slack,
email) when the user names one themselves.

## CRITICAL — preserving cron times
If the user says "7 AM" → "0 7 * * *". "6:30 AM" → "30 6 * * *". "every Monday at 9" → "0 9 * * 1". Never change the time. If you're not sure of the cron syntax, ask.

## Questioning rules
1. After the first message, infer as much as possible from what the user already said. Only ask about genuinely unclear things.
2. Ask ONE question per turn — the single most important unknown.
3. Preferred order: trigger type → data needed (tools) → output destination → schedule details → memory.
4. If the user explicitly asks for "all questions at once", you may list a few bullets in the reply — but still set "missing" to the list and keep asking just enough to fill it in.
5. When confidence ≥ 0.75 AND missing is empty: summarise as bullets under "Here's what I'll build:" and ask "Does this look right?" Set confidence ≥ 0.8.
6. If the user confirms the summary, set confidence to 0.95 and missing to [].

## Confidence calibration (be honest — this drives the UI)
- 0.0–0.2: Only a vague idea, almost nothing extracted yet
- 0.2–0.4: General purpose understood, no trigger or tools yet
- 0.4–0.6: Know trigger + purpose OR output + purpose
- 0.6–0.75: Know trigger, purpose, and output — filling in details
- 0.75–0.85: All required fields present — writing confirmation summary
- 0.85–1.0: User has confirmed — ready to generate

Update confidence EVERY turn. By turn 2 of a normal conversation you should be at least 0.3.

## Tone
- Never open with "Great!" or "Sure!" or "Certainly!" Just reply naturally.
- Warm and direct. Match the user's vocabulary.
- When writing the confirmation summary in "reply", use bullet points. Be concise.

## What goes in "tools"
Add a tool for each external data source the agent needs to access: emails, Slack messages, calendars, databases, web pages, APIs, files, CLI invocations. Use descriptive kebab-case names: "fetch-emails", "search-database", "get-weather", "notebooklm-add-source".`

// buildableGaps returns the things that must be present before an agent can
// actually be built, regardless of how confident the model says it is.
//
// Readiness used to be entirely self-attested: confidence over 0.8 and an
// empty `missing` list, both written by the model. It would declare a cron
// agent ready while leaving the cron expression blank — the summary said
// "every Friday at 4pm" in prose and the field was empty — and deploy then
// refused it. To the user that is the conversation saying yes and the product
// saying no, with nothing to do about it.
//
// So readiness now also checks the few things a build genuinely cannot do
// without. A gap found here goes back into the conversation as a question,
// which is the only place it can be answered.
func buildableGaps(u *BuilderUnderstanding) []string {
	if u == nil {
		return []string{"understanding"}
	}
	var gaps []string
	if strings.TrimSpace(u.Name) == "" {
		gaps = append(gaps, "agent name")
	}
	if strings.TrimSpace(u.SystemPrompt) == "" {
		gaps = append(gaps, "what the agent should actually do")
	}
	if u.Trigger != nil {
		switch strings.ToLower(strings.TrimSpace(u.Trigger.Type)) {
		case "cron":
			// A cron agent with no cron expression is the specific case that
			// passed the model's own readiness check and failed validation.
			if strings.TrimSpace(u.Trigger.Schedule) == "" {
				// Worded as an instruction rather than a topic. A smaller model
				// will happily write "every Friday at 4pm" into its summary and
				// leave trigger.schedule empty; naming the field and showing the
				// shape is what gets it filled in.
				gaps = append(gaps, "trigger.schedule must be a cron expression, e.g. \"0 16 * * 5\" for Friday at 4pm — set it from the time the user already gave")
			}
		}
	}
	return gaps
}

// looksLikeJSON reports whether the model was trying to answer in the JSON
// envelope, so a parse failure can be handled as a truncated machine reply
// rather than shown to the user as prose.
func looksLikeJSON(content string) bool {
	t := strings.TrimSpace(content)
	t = strings.TrimPrefix(t, "```json")
	t = strings.TrimPrefix(t, "```")
	return strings.HasPrefix(strings.TrimSpace(t), "{")
}

// cronFromPlainTime derives a daily cron from a time the user typed in
// ordinary words.
//
// Asking a model to emit "0 7 * * *" from "7am" works most of the time, and
// the times it does not the conversation stalls: the user has answered, the
// field is still empty, and they are asked again. A time of day is a small
// enough grammar to read directly, so the common case stops depending on the
// model at all. Anything it does not recognise is left alone for the model.
func cronFromPlainTime(text string) string {
	t := strings.ToLower(text)
	// 7am, 7 am, 7:30am, 07:30, at 7
	re := regexp.MustCompile(`\b(?:at\s+)?(\d{1,2})(?::(\d{2}))?\s*(am|pm)?\b`)
	m := re.FindStringSubmatch(t)
	if m == nil {
		return ""
	}
	hour, err := strconv.Atoi(m[1])
	if err != nil || hour < 0 || hour > 24 {
		return ""
	}
	minute := 0
	if m[2] != "" {
		if minute, err = strconv.Atoi(m[2]); err != nil || minute > 59 {
			return ""
		}
	}
	switch m[3] {
	case "pm":
		if hour < 12 {
			hour += 12
		}
	case "am":
		if hour == 12 {
			hour = 0
		}
	default:
		// A bare number with no am/pm is only a time if it could be one and the
		// sentence is about when something runs. Refusing here is safer than
		// scheduling an agent for an hour the user never said.
		if !strings.Contains(t, ":") && !strings.Contains(t, "o'clock") {
			return ""
		}
	}
	if hour > 23 {
		return ""
	}
	return fmt.Sprintf("%d %d * * *", minute, hour)
}
