// builder.go — conversational agent builder engine.
//
// The Builder turns a user's vague natural-language idea into a complete
// agent specification (SOUL.yaml) through a guided conversation. It uses a
// carefully crafted system prompt that:
//   - Asks exactly one question per turn (never lists of questions)
//   - Infers as much as possible from what the user already said
//   - Produces a structured UNDERSTANDING JSON block alongside every reply
//   - Knows when it has enough information to offer a confirmation and generate
//
// Each builder session is independent and lives in memory. Sessions expire
// after 2 hours of inactivity (cleaned up on next use).
package runtime

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"
	"sync"
	"time"
	"unicode"

	"go.uber.org/zap"

	"github.com/soulacy/soulacy/internal/agentprompt"
	"github.com/soulacy/soulacy/internal/llm"
)

// ── Types ─────────────────────────────────────────────────────────────────────

// BuilderUnderstanding is the structured spec the builder LLM builds up over
// the course of a conversation. It maps directly to a SOUL.yaml on generation.
type BuilderUnderstanding struct {
	Name         string          `json:"name"`
	Description  string          `json:"description"`
	Confidence   float64         `json:"confidence"`
	Trigger      *BuilderTrigger `json:"trigger"`
	Purpose      string          `json:"purpose"`
	SystemPrompt string          `json:"system_prompt"`
	Tools        []BuilderTool   `json:"tools"`
	Memory       *BuilderMemory  `json:"memory"`
	Outputs      []BuilderOutput `json:"outputs"`
	Missing      []string        `json:"missing"`
}

// BuilderTrigger describes how the agent is activated.
type BuilderTrigger struct {
	Type     string   `json:"type"`     // "cron" | "channel" | "manual"
	Schedule string   `json:"schedule"` // cron expression if type=cron
	Channels []string `json:"channels"` // e.g. ["whatsapp","http"]
}

// BuilderTool is an external capability the agent needs (becomes a tool in SOUL.yaml).
type BuilderTool struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

// BuilderMemory describes the agent's memory requirements.
type BuilderMemory struct {
	Needs bool   `json:"needs"`
	Scope string `json:"scope"` // "session" | "global"
}

// BuilderOutput describes where the agent sends its results.
type BuilderOutput struct {
	Channel     string `json:"channel"`
	Description string `json:"description"`
}

// BuilderResponse is returned to the gateway handler after each turn.
type BuilderResponse struct {
	SessionID     string                `json:"session_id"`
	Reply         string                `json:"reply"`
	Understanding *BuilderUnderstanding `json:"understanding"`
	Ready         bool                  `json:"ready"`
}

// builderSession holds the conversation history for one builder session.
type builderSession struct {
	ID            string
	History       []llm.ChatMessage
	Understanding *BuilderUnderstanding
	mu            sync.Mutex
	LastActive    time.Time
}

// ── Engine methods ────────────────────────────────────────────────────────────

// BuilderChat processes one turn of the agent builder conversation.
// provider is the LLM provider to use (e.g. "ollama", "openai").
// sessionID should be a UUID generated by the client for the first turn
// and reused for all subsequent turns.
// catalog is an optional pre-formatted string listing real tools available to
// agents (python files in ~/.soulacy/tools/, MCP server tools, built-ins).
// When non-empty, it's injected as an extra system message so the Builder LLM
// picks REAL tool names instead of inventing mcp__* placeholders.
func (e *Engine) BuilderChat(ctx context.Context, sessionID, message, provider, catalog string) (*BuilderResponse, error) {
	sess := e.getOrCreateBuilderSession(sessionID)

	sess.mu.Lock()
	sess.History = append(sess.History, llm.ChatMessage{Role: "user", Content: message})
	trimBuilderHistoryLocked(sess)
	msgs := buildBuilderMessages(sess.History)
	if catalog != "" {
		// Inject AFTER the system prompt, BEFORE the conversation history, so
		// every turn sees the catalog without baking it into stored history.
		header := llm.ChatMessage{Role: "system", Content: catalog}
		msgs = append([]llm.ChatMessage{msgs[0], header}, msgs[1:]...)
	}
	sess.mu.Unlock()

	e.log.Debug("builder chat",
		zap.String("session", sessionID),
		zap.String("preview", truncate(message, 60)),
	)

	// Request a single JSON object {reply, understanding} via the provider's
	// native structured-output mode. This is dramatically more reliable than
	// the legacy REPLY:/UNDERSTANDING: marker format — local models like
	// llama3.3:70b drift away from markers by turn 3-4, leaving the Blueprint
	// stuck at 0% confidence. JSON-mode is enforced by the provider itself.
	resp, err := e.llmRouter.Complete(ctx, provider, llm.CompletionRequest{
		Messages:       msgs,
		Temperature:    0.6,
		MaxTokens:      1500,
		ResponseFormat: "json_schema",
		JSONSchema:     builderResponseSchema,
	})
	if err != nil {
		return nil, fmt.Errorf("builder: llm: %w", err)
	}

	reply, understanding := parseBuilderResponse(resp.Content)

	sess.mu.Lock()
	sess.History = append(sess.History, llm.ChatMessage{Role: "assistant", Content: resp.Content})
	trimBuilderHistoryLocked(sess)
	if understanding != nil {
		sess.Understanding = understanding
	}
	sess.LastActive = time.Now()
	sess.mu.Unlock()

	ready := understanding != nil &&
		understanding.Confidence >= 0.8 &&
		len(understanding.Missing) == 0

	return &BuilderResponse{
		SessionID:     sessionID,
		Reply:         reply,
		Understanding: understanding,
		Ready:         ready,
	}, nil
}

// BuilderGenerate compiles a BuilderUnderstanding into a SOUL.yaml string
// and a JSON-serialisable agent map ready to POST to /api/v1/agents.
func (e *Engine) BuilderGenerate(u *BuilderUnderstanding, provider, model string) (soulYAML string, agentMap map[string]any) {
	soulYAML = generateSOULYAML(u, provider, model)
	agentMap = understandingToAgentMap(u, provider, model)
	return
}

// GetBuilderUnderstanding returns the current understanding for an existing
// builder session, or nil if the session doesn't exist yet.
func (e *Engine) GetBuilderUnderstanding(sessionID string) *BuilderUnderstanding {
	val, ok := e.builderSessions.Load(sessionID)
	if !ok {
		return nil
	}
	sess := val.(*builderSession)
	sess.mu.Lock()
	defer sess.mu.Unlock()
	return sess.Understanding
}

// DeleteBuilderSession removes a builder session from memory.
func (e *Engine) DeleteBuilderSession(sessionID string) {
	e.builderSessions.Delete(sessionID)
}

// ── Builder session management ────────────────────────────────────────────────

// Builder sessions are keyed by a CLIENT-SUPPLIED session id and were only ever
// removed by an explicit DELETE. LastActive was written on every turn and read
// nowhere; the package doc above promised a 2-hour expiry that did not exist. A
// caller holding builder:write could therefore pin unbounded memory by varying
// the id, and History grew without limit within a single session because the
// user message is appended BEFORE the LLM call — so even a failing provider
// still cost memory per request.
const (
	builderSessionTTL      = 2 * time.Hour
	maxBuilderSessions     = 200
	maxBuilderHistoryTurns = 60 // 30 exchanges; the Blueprint is summarised, not replayed
)

func (e *Engine) getOrCreateBuilderSession(id string) *builderSession {
	e.sweepBuilderSessions()
	val, _ := e.builderSessions.LoadOrStore(id, &builderSession{
		ID:         id,
		LastActive: time.Now(),
	})
	sess := val.(*builderSession)
	sess.mu.Lock()
	sess.LastActive = time.Now()
	sess.mu.Unlock()
	return sess
}

// sweepBuilderSessions drops sessions idle past the TTL, and — if the map is
// still over the cap after that — the least recently active ones. The cap is the
// part that actually bounds memory: a caller can create sessions far faster than
// the TTL retires them.
func (e *Engine) sweepBuilderSessions() {
	type aged struct {
		id   string
		last time.Time
	}
	cutoff := time.Now().Add(-builderSessionTTL)
	var live []aged
	e.builderSessions.Range(func(k, v any) bool {
		sess, ok := v.(*builderSession)
		if !ok {
			return true
		}
		sess.mu.Lock()
		last := sess.LastActive
		sess.mu.Unlock()
		if last.Before(cutoff) {
			e.builderSessions.Delete(k)
			return true
		}
		if id, ok := k.(string); ok {
			live = append(live, aged{id: id, last: last})
		}
		return true
	})
	// Note the "-1" and the "<": the sweep runs BEFORE the caller inserts, so it
	// has to leave room for the session about to be created. Trimming to exactly
	// maxBuilderSessions here means the map settles at maxBuilderSessions+1.
	if len(live) < maxBuilderSessions {
		return
	}
	sort.Slice(live, func(i, j int) bool { return live[i].last.Before(live[j].last) })
	for _, a := range live[:len(live)-maxBuilderSessions+1] {
		e.builderSessions.Delete(a.id)
	}
}

// trimBuilderHistoryLocked keeps the most recent turns. Caller holds sess.mu.
func trimBuilderHistoryLocked(sess *builderSession) {
	if len(sess.History) > maxBuilderHistoryTurns {
		sess.History = append([]llm.ChatMessage(nil), sess.History[len(sess.History)-maxBuilderHistoryTurns:]...)
	}
}

func buildBuilderMessages(history []llm.ChatMessage) []llm.ChatMessage {
	msgs := make([]llm.ChatMessage, 0, len(history)+1)
	msgs = append(msgs, llm.ChatMessage{Role: "system", Content: builderSystemPrompt})
	msgs = append(msgs, history...)
	return msgs
}

// ── Response parser ───────────────────────────────────────────────────────────

// tryParseBuilderJSON attempts to parse the LLM response as the canonical
// {reply, understanding} object. Tolerates code fences, leading prose, and
// trailing chatter — anything that still wraps a parseable JSON object.
func tryParseBuilderJSON(content string) (string, *BuilderUnderstanding, bool) {
	s := strings.TrimSpace(content)
	// Strip ```json fences if present.
	if strings.HasPrefix(s, "```") {
		s = strings.TrimPrefix(s, "```json")
		s = strings.TrimPrefix(s, "```")
		s = strings.TrimSuffix(s, "```")
		s = strings.TrimSpace(s)
	}
	// Find the outermost {...} — accommodates prefatory prose the model leaks.
	first := strings.Index(s, "{")
	last := strings.LastIndex(s, "}")
	if first < 0 || last <= first {
		return "", nil, false
	}
	var env struct {
		Reply         string                `json:"reply"`
		Understanding *BuilderUnderstanding `json:"understanding"`
	}
	if err := json.Unmarshal([]byte(s[first:last+1]), &env); err != nil {
		return "", nil, false
	}
	if env.Reply == "" && env.Understanding == nil {
		return "", nil, false
	}
	// If the model returned only understanding (no prose), synthesise a short
	// prompt so the user sees something in the chat instead of a blank bubble.
	if env.Reply == "" && env.Understanding != nil {
		if len(env.Understanding.Missing) > 0 {
			env.Reply = "Got it. Could you tell me about: " + strings.Join(env.Understanding.Missing, ", ") + "?"
		} else {
			env.Reply = "Got it — anything else I should know?"
		}
	}
	return env.Reply, env.Understanding, true
}

// builderResponseSchema is the JSON Schema we pass to the provider so the LLM
// is forced to emit a single object with `reply` and `understanding` fields.
// All providers (OpenAI, Anthropic, Gemini, Ollama ≥ 0.5) honor this via
// ResponseFormat=json_schema in CompletionRequest.
var builderResponseSchema = map[string]any{
	"type":                 "object",
	"additionalProperties": false,
	"required":             []string{"reply", "understanding"},
	"properties": map[string]any{
		"reply": map[string]any{
			"type":        "string",
			"description": "Your conversational message to the user — warm, direct, ONE question if anything is unclear.",
		},
		"understanding": map[string]any{
			"type": "object",
			"properties": map[string]any{
				"name":        map[string]any{"type": []string{"string", "null"}},
				"description": map[string]any{"type": []string{"string", "null"}},
				"confidence":  map[string]any{"type": "number"},
				"purpose":     map[string]any{"type": []string{"string", "null"}},
				"system_prompt": map[string]any{
					"type":        []string{"string", "null"},
					"description": "The full, detailed instructions the deployed agent will see on every run. MUST preserve the user's original procedure verbatim — including step-by-step numbered lists, specific cron times, chat IDs, URLs, API names, tool invocations. Multi-paragraph is encouraged. Do NOT summarise.",
				},
				"trigger": map[string]any{
					"type": []string{"object", "null"},
					"properties": map[string]any{
						"type":     map[string]any{"type": []string{"string", "null"}},
						"schedule": map[string]any{"type": []string{"string", "null"}},
						"channels": map[string]any{
							"type":  "array",
							"items": map[string]any{"type": "string"},
						},
					},
				},
				"tools": map[string]any{
					"type": "array",
					"items": map[string]any{
						"type": "object",
						"properties": map[string]any{
							"name":        map[string]any{"type": "string"},
							"description": map[string]any{"type": "string"},
						},
						"required": []string{"name", "description"},
					},
				},
				"memory": map[string]any{
					"type": []string{"object", "null"},
					"properties": map[string]any{
						"needs": map[string]any{"type": []string{"boolean", "null"}},
						"scope": map[string]any{"type": []string{"string", "null"}},
					},
				},
				"outputs": map[string]any{
					"type": "array",
					"items": map[string]any{
						"type": "object",
						"properties": map[string]any{
							"channel":     map[string]any{"type": "string"},
							"description": map[string]any{"type": "string"},
						},
					},
				},
				"missing": map[string]any{
					"type":  "array",
					"items": map[string]any{"type": "string"},
				},
			},
			"required": []string{"confidence"},
		},
	},
}

// parseBuilderResponse splits an LLM response into the conversational REPLY
// and the structured UNDERSTANDING JSON. Now JSON-mode first (the canonical
// shape produced by structured-output providers), with the legacy REPLY:/
// UNDERSTANDING: marker format as a fallback for any provider that ignores
// our response_format hint.
func parseBuilderResponse(content string) (reply string, understanding *BuilderUnderstanding) {
	// Path 1 — canonical: a single JSON object {reply, understanding}.
	if r, u, ok := tryParseBuilderJSON(content); ok {
		return r, u
	}

	// Path 2 — legacy: REPLY:/UNDERSTANDING: markers (kept for safety net).
	replyIdx := strings.Index(content, "REPLY:")
	underIdx := strings.Index(content, "UNDERSTANDING:")

	if replyIdx >= 0 && underIdx > replyIdx {
		reply = strings.TrimSpace(content[replyIdx+6 : underIdx])
		jsonPart := strings.TrimSpace(content[underIdx+14:])

		start := strings.Index(jsonPart, "{")
		end := strings.LastIndex(jsonPart, "}")
		if start >= 0 && end > start {
			u := &BuilderUnderstanding{}
			if err := json.Unmarshal([]byte(jsonPart[start:end+1]), u); err == nil {
				understanding = u
			}
		}
	} else if replyIdx >= 0 {
		reply = strings.TrimSpace(content[replyIdx+6:])
	} else {
		// No markers — use full content as reply, try to find embedded JSON
		reply = strings.TrimSpace(content)
		if start := strings.LastIndex(content, "```json"); start >= 0 {
			end := strings.LastIndex(content, "```")
			if end > start+7 {
				reply = strings.TrimSpace(content[:start])
				jsonStr := strings.TrimSpace(content[start+7 : end])
				u := &BuilderUnderstanding{}
				if err := json.Unmarshal([]byte(jsonStr), u); err == nil {
					understanding = u
				}
			}
		}
	}

	// Clean up reply — remove trailing code fences or JSON leakage
	if idx := strings.Index(reply, "```"); idx >= 0 {
		reply = strings.TrimSpace(reply[:idx])
	}

	return
}

// ── SOUL.yaml generator ───────────────────────────────────────────────────────

func generateSOULYAML(u *BuilderUnderstanding, provider, model string) string {
	id := sanitizeID(u.Name)
	if id == "" {
		id = "my-agent"
	}
	description := u.Description
	if description == "" {
		description = u.Purpose
	}
	humanName := toTitleCase(strings.ReplaceAll(id, "-", " "))

	triggerType := "channel"
	scheduleBlock := ""
	channelsBlock := "channels: [http]"

	if u.Trigger != nil {
		switch u.Trigger.Type {
		case "cron":
			triggerType = "cron"
			if u.Trigger.Schedule != "" {
				scheduleBlock = fmt.Sprintf("schedule: %q\n", u.Trigger.Schedule)
			}
			channelsBlock = ""
		case "channel":
			chs := u.Trigger.Channels
			if len(chs) == 0 {
				chs = []string{"http"}
			}
			channelsBlock = fmt.Sprintf("channels: [%s]", strings.Join(chs, ", "))
		case "manual":
			triggerType = "channel"
		}
	}

	// Prefer the detailed system_prompt the Builder produces — it captures the
	// user's full procedure verbatim (multi-step plans, specific cron times,
	// chat IDs, URLs). Fall back to purpose for older sessions that didn't
	// populate system_prompt.
	sysPrompt := u.SystemPrompt
	if sysPrompt == "" {
		sysPrompt = u.Purpose
	}
	if sysPrompt == "" {
		sysPrompt = "You are a helpful AI assistant."
	}
	sysPrompt = agentprompt.EnsureShared(sysPrompt)
	sysPromptIndented := strings.ReplaceAll(sysPrompt, "\n", "\n  ")

	toolsBlock := ""
	if len(u.Tools) > 0 {
		var sb strings.Builder
		sb.WriteString("\ntools:")
		for _, t := range u.Tools {
			sb.WriteString(fmt.Sprintf(
				"\n  - name: %s\n    description: %q\n    python_file: tools/%s.py\n    parameters:\n      type: object\n      properties: {}",
				t.Name, t.Description, t.Name))
		}
		toolsBlock = sb.String()
	}

	readScopes := "[session]"
	writeScopes := "[session]"
	if u.Memory != nil {
		if !u.Memory.Needs {
			readScopes = "[]"
			writeScopes = "[]"
		} else if u.Memory.Scope == "global" {
			readScopes = "[session, global]"
			writeScopes = "[session, global]"
		}
	}

	var out strings.Builder
	out.WriteString(fmt.Sprintf("id: %s\n", id))
	out.WriteString(fmt.Sprintf("name: %s\n", humanName))
	out.WriteString(fmt.Sprintf("description: %q\n", description))
	out.WriteString("version: \"1.0\"\n\n")
	out.WriteString(fmt.Sprintf("trigger: %s\n", triggerType))
	if scheduleBlock != "" {
		out.WriteString(scheduleBlock)
	}
	if channelsBlock != "" {
		out.WriteString(channelsBlock + "\n")
	}
	out.WriteString("\nsystem_prompt: |\n")
	out.WriteString(fmt.Sprintf("  %s\n", sysPromptIndented))
	out.WriteString("\nllm:\n")
	out.WriteString(fmt.Sprintf("  provider: %s\n", provider))
	out.WriteString(fmt.Sprintf("  model: %s\n", model))
	out.WriteString("  temperature: 0.7\n")
	out.WriteString("  max_tokens: 1024\n")
	if toolsBlock != "" {
		out.WriteString(toolsBlock)
		out.WriteString("\n")
	}
	out.WriteString("\nmemory:\n")
	out.WriteString(fmt.Sprintf("  read_scopes: %s\n", readScopes))
	out.WriteString(fmt.Sprintf("  write_scopes: %s\n", writeScopes))
	out.WriteString("  max_tokens: 50\n")
	out.WriteString("\nmax_turns: 10\n")
	out.WriteString("enabled: true\n")

	return out.String()
}

func understandingToAgentMap(u *BuilderUnderstanding, provider, model string) map[string]any {
	id := sanitizeID(u.Name)
	if id == "" {
		id = "my-agent"
	}
	description := u.Description
	if description == "" {
		description = u.Purpose
	}

	trigger := "channel"
	channels := []string{"http"}
	schedule := ""

	if u.Trigger != nil {
		switch u.Trigger.Type {
		case "cron":
			trigger = "cron"
			schedule = u.Trigger.Schedule
			channels = nil
		case "channel":
			if len(u.Trigger.Channels) > 0 {
				channels = u.Trigger.Channels
			}
		}
	}

	sysPrompt := u.SystemPrompt
	if sysPrompt == "" {
		sysPrompt = u.Purpose
	}
	if sysPrompt == "" {
		sysPrompt = "You are a helpful AI assistant."
	}

	readScopes := []string{"session"}
	writeScopes := []string{"session"}
	if u.Memory != nil && !u.Memory.Needs {
		readScopes = []string{}
		writeScopes = []string{}
	} else if u.Memory != nil && u.Memory.Scope == "global" {
		readScopes = []string{"session", "global"}
		writeScopes = []string{"session", "global"}
	}

	m := map[string]any{
		"id":            id,
		"name":          toTitleCase(strings.ReplaceAll(id, "-", " ")),
		"description":   description,
		"version":       "1.0",
		"trigger":       trigger,
		"system_prompt": sysPrompt,
		"llm": map[string]any{
			"provider":    provider,
			"model":       model,
			"temperature": 0.7,
			"max_tokens":  1024,
		},
		"memory": map[string]any{
			"read_scopes":  readScopes,
			"write_scopes": writeScopes,
			"max_tokens":   50,
		},
		"max_turns": 10,
		"enabled":   true,
	}
	if trigger == "channel" && len(channels) > 0 {
		m["channels"] = channels
	}
	if schedule != "" {
		// agent.Definition.Schedule is *Schedule{Cron, At, Timeout} — use object form.
		m["schedule"] = map[string]any{"cron": schedule}
	}
	if len(u.Tools) > 0 {
		tools := make([]map[string]any, len(u.Tools))
		for i, t := range u.Tools {
			tools[i] = map[string]any{
				"name":        t.Name,
				"description": t.Description,
				"python_file": fmt.Sprintf("tools/%s.py", t.Name),
				"parameters": map[string]any{
					"type":       "object",
					"properties": map[string]any{},
				},
			}
		}
		m["tools"] = tools
	}
	return m
}

// ── String helpers ────────────────────────────────────────────────────────────

func sanitizeID(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	var out strings.Builder
	prevHyphen := false
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			out.WriteRune(r)
			prevHyphen = false
		} else if r == '-' || r == ' ' || r == '_' {
			if !prevHyphen && out.Len() > 0 {
				out.WriteRune('-')
				prevHyphen = true
			}
		}
	}
	result := strings.TrimSuffix(out.String(), "-")
	if len(result) > 64 {
		result = result[:64]
	}
	return result
}

func toTitleCase(s string) string {
	words := strings.Fields(s)
	for i, w := range words {
		if len(w) > 0 {
			runes := []rune(w)
			runes[0] = unicode.ToUpper(runes[0])
			words[i] = string(runes)
		}
	}
	return strings.Join(words, " ")
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}

// ── System prompt ─────────────────────────────────────────────────────────────

const builderSystemPrompt = `You are the Soulacy Agent Builder — a conversational assistant that helps people design AI agents through friendly dialogue.

## Your mission
Turn a user's vague idea into a precise, deployable agent specification. Do this through targeted questions — one at a time, never a list. Speak plain English. Never use technical jargon unless the user uses it first.

## REQUIRED response format
Every single response MUST be a single JSON object with exactly two top-level fields:

{
  "reply":         "<your conversational message — warm, direct, one question if anything is unclear>",
  "understanding": { ... see schema below ... }
}

Return ONLY this JSON object. No prose before or after. No code fences. No markdown headers. The platform will display the "reply" field to the user; the "understanding" field is read programmatically and MUST be updated every turn (never omit).

## understanding schema
{
  "name":        "kebab-case-agent-name" | null,
  "description": "one-sentence summary of what the agent does" | null,
  "confidence":  0.0,
  "purpose":     "in plain English, what should the LLM core do?" | null,
  "system_prompt": "the FULL detailed instructions the deployed agent will see — see rules below" | null,
  "trigger": {
    "type":     "cron" | "channel" | "manual" | null,
    "schedule": "cron expression like '0 7 * * *'" | null,
    "channels": ["http", "telegram", ...]
  } | null,
  "tools":   [{"name": "kebab-case", "description": "..."}],
  "memory":  {"needs": true | false | null, "scope": "session" | "global" | null} | null,
  "outputs": [{"channel": "telegram | http | ...", "description": "..."}],
  "missing": ["short label for each thing still unclear"]
}

## CRITICAL — preserving the user's procedure
The "system_prompt" field is the actual instructions the deployed agent will see on every run. It is NOT a summary — it is the operating procedure.
- Begin every system_prompt with the shared Soulacy Agent Operating Contract, then append a role-specific "## Agent Role" section.
- Copy the user's numbered steps VERBATIM into system_prompt.
- Preserve every specific value the user gave: cron times, dates, chat IDs, URLs, API endpoints, tool names, regex patterns, search queries.
- If the user said "every morning at 7 AM", the cron MUST be "0 7 * * *" (not 8 or 9). NEVER change a time the user gave you.
- If the user said "send to Telegram chat 8546291328", put that exact ID into system_prompt and mention it in the tool's description.
- Multi-paragraph system_prompts are encouraged when the user described a multi-step procedure. Don't compress.
- Add a final "Important:" paragraph noting failure modes and constraints you inferred.

## CRITICAL — preserving cron times
If the user says "7 AM" → "0 7 * * *". "6:30 AM" → "30 6 * * *". "every Monday at 9" → "0 9 * * 1". Never change the time. If you're not sure of the cron syntax, ask.

## Questioning rules
1. After the first message, infer as much as possible from what the user already said. Only ask about genuinely unclear things.
2. Ask ONE question per turn — the single most important unknown.
3. Preferred order: trigger type → data needed (tools) → output destination → schedule details → memory.
4. If the user explicitly asks for "all questions at once", you may list a few bullets in the reply — but still set "missing" to the list and keep asking just enough to fill it in.
5. When confidence ≥ 0.75 AND missing is empty: summarise as bullets under "Here's what I'll build:" and ask "Does this look right?" Set confidence ≥ 0.8.
6. If the user confirms the summary, set confidence to 0.95 and missing to [].

## Confidence calibration (be honest — this drives the UI)
- 0.0–0.2: Only a vague idea, almost nothing extracted yet
- 0.2–0.4: General purpose understood, no trigger or tools yet
- 0.4–0.6: Know trigger + purpose OR output + purpose
- 0.6–0.75: Know trigger, purpose, and output — filling in details
- 0.75–0.85: All required fields present — writing confirmation summary
- 0.85–1.0: User has confirmed — ready to generate

Update confidence EVERY turn. By turn 2 of a normal conversation you should be at least 0.3.

## Tone
- Never open with "Great!" or "Sure!" or "Certainly!" Just reply naturally.
- Warm and direct. Match the user's vocabulary.
- When writing the confirmation summary in "reply", use bullet points. Be concise.

## What goes in "tools"
Add a tool for each external data source the agent needs to access: emails, Slack messages, calendars, databases, web pages, APIs, files, CLI invocations. Use descriptive kebab-case names: "fetch-emails", "search-database", "get-weather", "notebooklm-add-source".`
