// Package buildtool builds custom ("flavored") soulacy binaries with
// extra drivers compiled in (Story E12; promoted from scripts/soulacybuild
// to the `soulacy build` subcommand in Story 19b). Third-party channels,
// providers, queue/vector backends, reasoning strategies, and package
// registries self-register with the SDK factory registries from init();
// a custom distribution is their packages blank-imported into cmd/soulacy
// plus a normal verified build.
//
// Steps: (1) `go get module@version` for each extra module; (2) write
// cmd/soulacy/builtins_extra.go blank-importing them; (3) run the
// conformance/registry test gates (E11 kits + TestAllBuiltinsRegistered)
// unless skip-verify; (4) `go build` the single static binary.
// Must run from the repository root.
package buildtool

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// ExtraFile is the generated blank-import file for flavored builds.
const ExtraFile = "cmd/soulacy/builtins_extra.go"

// Run performs the flavored build. with holds module[@version] specs;
// out is the output binary path.
func Run(with []string, out string, skipVerify, keep bool) error {
	if _, err := os.Stat("cmd/soulacy"); err != nil {
		return fmt.Errorf("run from the repository root (cmd/soulacy not found): %w", err)
	}

	// 1. Parse modules and write the extra blank-import file.
	var modules []string
	for _, w := range with {
		mod, ver, err := parseWith(w)
		if err != nil {
			return err
		}
		modules = append(modules, mod)
		// 2. Resolve the module into go.mod/go.sum.
		fmt.Printf("→ go get %s@%s\n", mod, ver)
		if err := runCmd("go", "get", mod+"@"+ver); err != nil {
			return fmt.Errorf("resolve %s@%s: %w", mod, ver, err)
		}
	}
	if src := generateExtraImports(modules); src != nil {
		if err := os.WriteFile(ExtraFile, src, 0644); err != nil {
			return fmt.Errorf("write %s: %w", ExtraFile, err)
		}
		fmt.Printf("→ wrote %s (%d extra driver(s))\n", ExtraFile, len(modules))
		if !keep {
			defer os.Remove(ExtraFile)
		}
	}

	// 3. Verification gates: the E11 conformance kits run against every
	// compiled-in driver's package tests, and TestAllBuiltinsRegistered
	// proves the registries are fully populated in THIS build.
	if !skipVerify {
		fmt.Println("→ verification: conformance kits + registry pin")
		if err := runCmd("go", "test", "-run", "TestConformance",
			"./internal/llm/", "./internal/channels/"); err != nil {
			return fmt.Errorf("conformance gate failed: %w", err)
		}
		// Sidecar protocol kit against the reference sidecars (skips
		// gracefully when python3 is unavailable on the build host).
		if err := runCmd("go", "test", "-run", "TestRunConformance|TestPoCVoiceSidecarConformance",
			"./internal/channels/external/"); err != nil {
			return fmt.Errorf("sidecar conformance gate failed: %w", err)
		}
		if err := runCmd("go", "test", "-run", "TestAllBuiltinsRegistered", "./cmd/soulacy/"); err != nil {
			return fmt.Errorf("registry gate failed: %w", err)
		}
	}

	// 4. Single static binary.
	if dir := filepath.Dir(out); dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0755); err != nil {
			return fmt.Errorf("create output dir: %w", err)
		}
	}
	fmt.Printf("→ go build -o %s ./cmd/soulacy\n", out)
	if err := runCmd("go", "build", "-trimpath", "-o", out, "./cmd/soulacy"); err != nil {
		return fmt.Errorf("build: %w", err)
	}
	fmt.Printf("✓ flavored binary ready: %s\n", out)
	return nil
}

// parseWith splits "module[@version]"; version defaults to "latest".
func parseWith(s string) (module, version string, err error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return "", "", fmt.Errorf("--with: empty module spec")
	}
	module, version = s, "latest"
	if i := strings.LastIndex(s, "@"); i >= 0 {
		module, version = s[:i], s[i+1:]
	}
	if module == "" || version == "" {
		return "", "", fmt.Errorf("--with %q: want module[@version]", s)
	}
	if strings.ContainsAny(module, " \t\"'") {
		return "", "", fmt.Errorf("--with %q: invalid module path", s)
	}
	return module, version, nil
}

// generateExtraImports renders the blank-import file for the extra driver
// modules. Returns nil when there is nothing to import.
func generateExtraImports(modules []string) []byte {
	if len(modules) == 0 {
		return nil
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by scripts/soulacybuild. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Extra drivers compiled into this flavored binary (Story E12). Their\n")
	b.WriteString("// init() functions self-register with the SDK factory registries.\n")
	b.WriteString("package main\n\nimport (\n")
	for _, m := range modules {
		fmt.Fprintf(&b, "\t_ %q\n", m)
	}
	b.WriteString(")\n")
	return b.Bytes()
}

func runCmd(name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Env = os.Environ()
	return cmd.Run()
}
