// Command genbuiltins writes the blank-import registration file that links
// every built-in driver into the soulacy binary (Story E10).
//
// Built-in drivers self-register with the SDK factory registries from
// init(); this file is what guarantees those init() functions actually run
// in the shipped binary. The E12 flavored-binary tool extends the same
// mechanism with third-party modules.
//
// Usage (from cmd/soulacy):
//
//	go generate ./...   — or directly: go run ../../scripts/genbuiltins -out builtins_gen.go
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
)

// builtins is the canonical list of driver packages compiled into the
// standard binary. Adding a driver = adding a line here + `go generate`.
var builtins = []string{
	// channels
	"github.com/soulacy/soulacy/internal/channels/discord",
	"github.com/soulacy/soulacy/internal/channels/email",
	"github.com/soulacy/soulacy/internal/channels/googlechat",
	"github.com/soulacy/soulacy/internal/channels/slack",
	"github.com/soulacy/soulacy/internal/channels/teams",
	"github.com/soulacy/soulacy/internal/channels/telegram",
	"github.com/soulacy/soulacy/internal/channels/webhook",
	"github.com/soulacy/soulacy/internal/channels/whatsapp",
	// external storage sidecars (vector + queue "external" factories, E24)
	"github.com/soulacy/soulacy/internal/extstorage",
	// llm providers (ollama / openai / anthropic / gemini live in one package)
	"github.com/soulacy/soulacy/internal/llm",
	// queue backends
	"github.com/soulacy/soulacy/internal/queue/memory",
	"github.com/soulacy/soulacy/internal/queue/nats",
	// package registries (http / git live in one package)
	"github.com/soulacy/soulacy/internal/pkgregistry",
	// reasoning strategies (react / plan_execute live in one package)
	"github.com/soulacy/soulacy/internal/reasoning",
	// vector backends
	"github.com/soulacy/soulacy/internal/vector/qdrant",
	"github.com/soulacy/soulacy/internal/vector/sqlitevec",
}

func main() {
	out := flag.String("out", "builtins_gen.go", "output file path")
	flag.Parse()

	var b bytes.Buffer
	b.WriteString("// Code generated by scripts/genbuiltins. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Blank imports link every built-in driver's init() self-registration\n")
	b.WriteString("// into the binary (Story E10). Regenerate with: go generate ./...\n")
	b.WriteString("package main\n\nimport (\n")
	for _, pkg := range builtins {
		fmt.Fprintf(&b, "\t_ %q\n", pkg)
	}
	b.WriteString(")\n")

	if err := os.WriteFile(*out, b.Bytes(), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "genbuiltins: %v\n", err)
		os.Exit(1)
	}
}
