// Code generated by scripts/genbuiltins. DO NOT EDIT.
//
// Blank imports link every built-in driver's init() self-registration
// into the binary (Story E10). Regenerate with: go generate ./...
package main

import (
	_ "github.com/soulacy/soulacy/internal/channels/discord"
	_ "github.com/soulacy/soulacy/internal/channels/email"
	_ "github.com/soulacy/soulacy/internal/channels/googlechat"
	_ "github.com/soulacy/soulacy/internal/channels/slack"
	_ "github.com/soulacy/soulacy/internal/channels/teams"
	_ "github.com/soulacy/soulacy/internal/channels/telegram"
	_ "github.com/soulacy/soulacy/internal/channels/webhook"
	_ "github.com/soulacy/soulacy/internal/channels/whatsapp"
	_ "github.com/soulacy/soulacy/internal/extstorage"
	_ "github.com/soulacy/soulacy/internal/llm"
	_ "github.com/soulacy/soulacy/internal/queue/memory"
	_ "github.com/soulacy/soulacy/internal/queue/nats"
	_ "github.com/soulacy/soulacy/internal/pkgregistry"
	_ "github.com/soulacy/soulacy/internal/reasoning"
	_ "github.com/soulacy/soulacy/internal/vector/qdrant"
	_ "github.com/soulacy/soulacy/internal/vector/sqlitevec"
)
