package reasoning

// The graph that every static check passed and that died on its first run.
//
// Weekday Market Digest, generated by Studio and saved to disk:
// gather_data → fan_out_specialists(parallel, join: all) → three analysts →
// editor → end. Studio reported VALID, 0 blockers, 0 warnings. The dry run said:
//
//	flow: node "fan_out_specialists": branch "fundamentals_analyst":
//	  flow: node "editor": render input: execute template:
//	  executing "" at <.risk_analysis>: map has no entry for key "risk_analysis"
//
// `join: all` said HOW to wait. Nothing said WHERE the branches stop, so each
// one walked to the end of the graph and ran its own editor with only its own
// analysis in scope.
//
// Studio now blocks this at authoring time. These tests cover the graphs that
// never pass through Studio: the copy already saved on the user's disk, YAML
// written by hand, an imported template. All of them reach CompileFlow.

import (
	"strings"
	"testing"

	sdkr "github.com/soulacy/soulacy/sdk/reasoning"
)

// digestSpec is the live graph. barrier == "" reproduces what was saved.
func digestSpec(barrier string) sdkr.FlowSpec {
	return sdkr.FlowSpec{
		Entry: "gather_data",
		Nodes: []sdkr.FlowNode{
			{ID: "gather_data", Kind: sdkr.FlowNodeAgent, Agent: "data_gatherer", Output: "data"},
			{ID: "fan_out_specialists", Kind: sdkr.FlowNodeParallel, Join: sdkr.JoinAll, JoinNode: barrier},
			{ID: "fundamentals_analyst", Kind: sdkr.FlowNodeAgent, Agent: "fundamentals_analyst",
				Input: "Read {{ .data }}", Output: "fundamentals_analysis"},
			{ID: "risk_analyst", Kind: sdkr.FlowNodeAgent, Agent: "risk_analyst",
				Input: "Read {{ .data }}", Output: "risk_analysis"},
			{ID: "sentiment_analyst", Kind: sdkr.FlowNodeAgent, Agent: "sentiment_analyst",
				Input: "Read {{ .data }}", Output: "sentiment_analysis"},
			{ID: "editor", Kind: sdkr.FlowNodeAgent, Agent: "editor",
				Input:  "Combine {{ .fundamentals_analysis }} {{ .risk_analysis }} {{ .sentiment_analysis }}",
				Output: "briefing"},
		},
		Edges: []sdkr.FlowEdge{
			{From: "gather_data", To: "fan_out_specialists"},
			{From: "fan_out_specialists", To: "fundamentals_analyst"},
			{From: "fan_out_specialists", To: "risk_analyst"},
			{From: "fan_out_specialists", To: "sentiment_analyst"},
			{From: "fundamentals_analyst", To: "editor"},
			{From: "risk_analyst", To: "editor"},
			{From: "sentiment_analyst", To: "editor"},
			{From: "editor", To: "end"},
		},
	}
}

func TestCompileFlow_RefusesTheGraphThatDiedOnItsFirstRun(t *testing.T) {
	_, err := CompileFlow(digestSpec(""))
	if err == nil {
		t.Fatal("compiled a flow whose editor runs three times, each missing two of its three inputs")
	}
	msg := err.Error()
	for _, want := range []string{"editor", "fan_out_specialists", "join_node"} {
		if !strings.Contains(msg, want) {
			t.Errorf("the error never mentions %q, so the reader cannot act on it: %s", want, msg)
		}
	}
}

// The whole point of the message is that it names the edit. A reader who has to
// work out the barrier themselves is no better off than with the template error.
func TestCompileFlow_NamesTheBarrierToSet(t *testing.T) {
	_, err := CompileFlow(digestSpec(""))
	if err == nil {
		t.Fatal("expected a scope error")
	}
	if !strings.Contains(err.Error(), "join_node: editor") {
		t.Errorf("the error does not spell out the fix: %s", err.Error())
	}
}

func TestCompileFlow_AcceptsTheSameGraphOnceTheBarrierIsNamed(t *testing.T) {
	if _, err := CompileFlow(digestSpec("editor")); err != nil {
		t.Fatalf("rejected the repaired graph: %v", err)
	}
}

// A barrier set past the real convergence point fails identically — the branches
// still run the editor. This shape passes every existing check, including the
// "can each branch reach the barrier?" rule, because it can.
func TestCompileFlow_CatchesABarrierSetTooLate(t *testing.T) {
	spec := digestSpec("deliver")
	spec.Nodes = append(spec.Nodes, sdkr.FlowNode{
		ID: "deliver", Kind: sdkr.FlowNodeTool, Tool: "channel.send", Input: "{{ .briefing }}"})
	for i := range spec.Edges {
		if spec.Edges[i].From == "editor" {
			spec.Edges[i].To = "deliver"
		}
	}
	spec.Edges = append(spec.Edges, sdkr.FlowEdge{From: "deliver", To: "end"})

	_, err := CompileFlow(spec)
	if err == nil {
		t.Fatal("accepted a barrier one node past the convergence point — the editor still runs per branch")
	}
	if !strings.Contains(err.Error(), "editor") {
		t.Errorf("the error should point at the node that runs too many times: %s", err.Error())
	}
}

// Branches that genuinely end apart are a legitimate shape: three notifications,
// no summary. Each reads only what it was given.
func TestCompileFlow_AllowsBranchesThatEndSeparately(t *testing.T) {
	spec := sdkr.FlowSpec{
		Entry: "prep",
		Nodes: []sdkr.FlowNode{
			{ID: "prep", Kind: sdkr.FlowNodeLLM, Output: "report"},
			{ID: "fan", Kind: sdkr.FlowNodeParallel, Join: sdkr.JoinAll},
			{ID: "email", Kind: sdkr.FlowNodeTool, Tool: "channel.send", Input: "{{ .report }}"},
			{ID: "slack", Kind: sdkr.FlowNodeTool, Tool: "channel.send", Input: "{{ .report }}"},
		},
		Edges: []sdkr.FlowEdge{
			{From: "prep", To: "fan"},
			{From: "fan", To: "email"}, {From: "fan", To: "slack"},
		},
	}
	if _, err := CompileFlow(spec); err != nil {
		t.Fatalf("refused a fan-out that was never meant to reconverge: %v", err)
	}
}

// The same node reached from every branch is fine as long as it reads only what
// its own branch and the upstream produced. This is the map/notify pattern —
// one send per branch, on purpose — and it must not be swept up by the check.
func TestCompileFlow_AllowsASharedTailThatReadsNoSiblingOutput(t *testing.T) {
	spec := sdkr.FlowSpec{
		Entry: "prep",
		Nodes: []sdkr.FlowNode{
			{ID: "prep", Kind: sdkr.FlowNodeLLM, Output: "report"},
			{ID: "fan", Kind: sdkr.FlowNodeParallel, Join: sdkr.JoinAll},
			{ID: "a", Kind: sdkr.FlowNodeLLM, Input: "{{ .report }}", Output: "a_out"},
			{ID: "b", Kind: sdkr.FlowNodeLLM, Input: "{{ .report }}", Output: "b_out"},
			// Reads the upstream var only — legal in both branches.
			{ID: "notify", Kind: sdkr.FlowNodeTool, Tool: "channel.send", Input: "Done: {{ .report }}"},
		},
		Edges: []sdkr.FlowEdge{
			{From: "prep", To: "fan"},
			{From: "fan", To: "a"}, {From: "fan", To: "b"},
			{From: "a", To: "notify"}, {From: "b", To: "notify"},
		},
	}
	if _, err := CompileFlow(spec); err != nil {
		t.Fatalf("refused a per-branch notification that reads nothing from its siblings: %v", err)
	}
}

// Reading your own branch's earlier output is the ordinary case.
func TestCompileFlow_AllowsAReadWithinTheSameBranch(t *testing.T) {
	spec := sdkr.FlowSpec{
		Entry: "fan",
		Nodes: []sdkr.FlowNode{
			{ID: "fan", Kind: sdkr.FlowNodeParallel, Join: sdkr.JoinAll},
			{ID: "draft", Kind: sdkr.FlowNodeLLM, Output: "draft_text"},
			{ID: "polish", Kind: sdkr.FlowNodeLLM, Input: "Tidy {{ .draft_text }}", Output: "polished"},
			{ID: "other", Kind: sdkr.FlowNodeLLM, Output: "other_out"},
		},
		Edges: []sdkr.FlowEdge{
			{From: "fan", To: "draft"}, {From: "fan", To: "other"},
			{From: "draft", To: "polish"},
		},
	}
	if _, err := CompileFlow(spec); err != nil {
		t.Fatalf("refused a branch reading a value it produced itself: %v", err)
	}
}

// A var no node writes is a typo or a run-time input, and belongs to the checks
// that own dangling references. Claiming it as a scope error would misdiagnose it.
func TestCompileFlow_DoesNotClaimAnUnproducedVarIsAScopeProblem(t *testing.T) {
	spec := sdkr.FlowSpec{
		Entry: "fan",
		Nodes: []sdkr.FlowNode{
			{ID: "fan", Kind: sdkr.FlowNodeParallel, Join: sdkr.JoinAll},
			{ID: "a", Kind: sdkr.FlowNodeLLM, Input: "{{ .nobody_writes_this }}", Output: "a_out"},
			{ID: "b", Kind: sdkr.FlowNodeLLM, Output: "b_out"},
		},
		Edges: []sdkr.FlowEdge{{From: "fan", To: "a"}, {From: "fan", To: "b"}},
	}
	if _, err := CompileFlow(spec); err != nil {
		t.Fatalf("reported a dangling reference as a branch-scope error: %v", err)
	}
}

// The trigger payload is seeded into every branch's vars by the runtime.
func TestCompileFlow_AllowsBuiltinsInsideBranches(t *testing.T) {
	spec := sdkr.FlowSpec{
		Entry: "fan",
		Nodes: []sdkr.FlowNode{
			{ID: "fan", Kind: sdkr.FlowNodeParallel, Join: sdkr.JoinAll},
			{ID: "a", Kind: sdkr.FlowNodeLLM, Input: "{{ .trigger.text }}", Output: "a_out"},
			{ID: "b", Kind: sdkr.FlowNodeLLM, Input: "{{ .history }}", Output: "b_out"},
		},
		Edges: []sdkr.FlowEdge{{From: "fan", To: "a"}, {From: "fan", To: "b"}},
	}
	if _, err := CompileFlow(spec); err != nil {
		t.Fatalf("treated a runtime-seeded builtin as a missing sibling output: %v", err)
	}
}

// Inline Python reads its vars through `inputs`, not through a template. The
// same scope rule applies, so the same check has to see them.
func TestCompileFlow_CatchesTheCrossBranchReadInInlinePython(t *testing.T) {
	spec := sdkr.FlowSpec{
		Entry: "fan",
		Nodes: []sdkr.FlowNode{
			{ID: "fan", Kind: sdkr.FlowNodeParallel, Join: sdkr.JoinAll},
			{ID: "a", Kind: sdkr.FlowNodeLLM, Output: "a_out"},
			{ID: "b", Kind: sdkr.FlowNodeLLM, Output: "b_out"},
			{ID: "merge", Kind: sdkr.FlowNodePython,
				Code: "result = inputs.get('a_out') + inputs['b_out']", Output: "merged"},
		},
		Edges: []sdkr.FlowEdge{
			{From: "fan", To: "a"}, {From: "fan", To: "b"},
			{From: "a", To: "merge"}, {From: "b", To: "merge"},
		},
	}
	if _, err := CompileFlow(spec); err == nil {
		t.Fatal("a python merge step inside both branches was accepted")
	}
}

// A for_each template is rendered in the same scope as the node's input.
func TestCompileFlow_CatchesTheCrossBranchReadInForEach(t *testing.T) {
	spec := sdkr.FlowSpec{
		Entry: "fan",
		Nodes: []sdkr.FlowNode{
			{ID: "fan", Kind: sdkr.FlowNodeParallel, Join: sdkr.JoinAll},
			{ID: "a", Kind: sdkr.FlowNodeLLM, Output: "a_out"},
			{ID: "b", Kind: sdkr.FlowNodeLLM, Output: "b_items"},
			{ID: "each", Kind: sdkr.FlowNodeLLM, ForEach: "{{ toJson .b_items }}", Output: "per_item"},
		},
		Edges: []sdkr.FlowEdge{
			{From: "fan", To: "a"}, {From: "fan", To: "b"},
			{From: "a", To: "each"},
		},
	}
	if _, err := CompileFlow(spec); err == nil {
		t.Fatal("a for_each ranging over a sibling branch's output was accepted")
	}
}

// Two graphs that differ only in node ORDER must produce the same verdict and
// the same message, or the same mistake reads differently depending on how the
// file happened to be written.
func TestCompileFlow_ReportsTheSameScopeErrorRegardlessOfNodeOrder(t *testing.T) {
	a := digestSpec("")
	b := digestSpec("")
	b.Nodes[2], b.Nodes[4] = b.Nodes[4], b.Nodes[2]

	_, ea := CompileFlow(a)
	_, eb := CompileFlow(b)
	if ea == nil || eb == nil {
		t.Fatalf("one ordering compiled: a=%v b=%v", ea, eb)
	}
	if ea.Error() != eb.Error() {
		t.Errorf("the message depends on node order:\n a: %s\n b: %s", ea, eb)
	}
}

func TestTemplateVars_ReadsTheLeadingIdentifierOfAChain(t *testing.T) {
	got := TemplateVars("{{ .report.title }} and {{ toJson .items }} and {{ .items }}")
	want := []string{"report", "items"}
	if len(got) != len(want) {
		t.Fatalf("got %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("got %v, want %v", got, want)
		}
	}
}
