// promote.go — Studio "promote to reusable tool" (Tier B). Turns an inline
// Custom Python node's code into a deployable *.py tool file that the catalog
// watcher picks up from the workspace tools dir.
//
// Only the pure mapping (name -> filename + file contents) lives here so it is
// unit-testable without disk or an HTTP server. The gateway endpoint writes the
// returned contents to <workspace>/tools/<filename> and rewires the node.
//
// SECURITY NOTE: promoting beyond-guardrail code (system/network) escalates it
// out of the per-case code-consent loop into an operator-trusted tool file. The
// promote endpoint MUST therefore require the same consent the inline node would
// (see docs/STUDIO_PYTHON_TOOLS.md §13) before writing the file — promotion is a
// deliberate, consented escalation, not a bypass.
package studio

import (
	"fmt"
	"strings"
)

// PromotedTool is the result of building a deployable tool from inline code.
type PromotedTool struct {
	// Name is the registered tool name (also the *.py stem and the Python entry
	// function name) — a valid Python identifier derived from the requested name.
	Name string
	// Filename is "<Name>.py".
	Filename string
	// Contents is the full file body to write to the tools dir.
	Contents string
}

// BuildPromotedTool maps a requested tool name + an inline Custom Python body
// (which must define `def run(inputs):`) into a deployable tool file.
//
// The deployed-tool call convention is `getattr(module, <toolname>)(**kwargs)`
// (internal/runtime/engine.go executePythonTool): the entry function's name
// equals the tool name and it receives keyword args. We therefore name the
// entry function after the (identifier-safe) tool name and have it forward the
// kwargs dict to the original `run(inputs)` body, so the promoted tool behaves
// exactly like the inline node did.
func BuildPromotedTool(name, code string) (PromotedTool, error) {
	fn := toPyIdent(name)
	if fn == "" {
		return PromotedTool{}, fmt.Errorf("studio: cannot derive a tool name from %q", name)
	}
	if strings.TrimSpace(code) == "" {
		return PromotedTool{}, fmt.Errorf("studio: cannot promote an empty code block")
	}
	if !strings.Contains(code, "def run(") {
		return PromotedTool{}, fmt.Errorf("studio: code must define a run(inputs) function to promote")
	}

	var b strings.Builder
	fmt.Fprintf(&b, "\"\"\"\n%s — Soulacy tool promoted from a Studio Custom Python block.\n\n", fn)
	b.WriteString("Auto-generated by Studio. The original inline run(inputs) body is preserved\n")
	fmt.Fprintf(&b, "below; the %s(**inputs) entry point adapts the Soulacy tool-call convention\n", fn)
	b.WriteString("(keyword args) to that body so the tool behaves exactly like the inline node.\n\"\"\"\n\n")
	b.WriteString(strings.TrimRight(code, "\n"))
	b.WriteString("\n\n\n")
	fmt.Fprintf(&b, "def %s(**inputs):\n    return run(inputs)\n", fn)

	return PromotedTool{Name: fn, Filename: fn + ".py", Contents: b.String()}, nil
}

// toPyIdent turns an arbitrary name into a safe lowercase Python identifier:
// non-alphanumeric runs collapse to "_", a leading digit is prefixed with "_",
// and the result is trimmed of edge underscores (then re-padded if it became
// empty/leading-digit). Returns "" only for an all-empty input.
func toPyIdent(name string) string {
	s := strings.ToLower(strings.TrimSpace(name))
	var out strings.Builder
	prevUnderscore := false
	for _, r := range s {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			out.WriteRune(r)
			prevUnderscore = false
		} else if !prevUnderscore {
			out.WriteByte('_')
			prevUnderscore = true
		}
	}
	id := strings.Trim(out.String(), "_")
	if id == "" {
		return ""
	}
	if id[0] >= '0' && id[0] <= '9' {
		id = "_" + id
	}
	return id
}
